/**
 * Display names for the `source` tag on burn events — one per CLI adapter
 * (cli/src/adapters), plus the proxy and the open sink. The server accepts any
 * [a-z0-9-] tag, so an unknown one still renders, just as its raw id.
 */
export const SOURCE_LABELS: Record<string, string> = {
  "claude-code": "Claude Code",
  codex: "Codex",
  cursor: "Cursor",
  gemini: "Gemini CLI",
  copilot: "Copilot CLI",
  "copilot-desktop": "Copilot",
  "copilot-session-store": "Copilot CLI",
  "copilot-vscode": "Copilot in VS Code",
  opencode: "opencode",
  pi: "pi",
  amp: "Amp",
  droid: "Factory Droid",
  cline: "Cline",
  roocode: "Roo Code",
  kilocode: "Kilo Code",
  kilo: "Kilo CLI",
  goose: "Goose",
  zed: "Zed",
  qwen: "Qwen Code",
  kimi: "Kimi CLI",
  hermes: "Hermes",
  openclaw: "OpenClaw",
  antigravity: "Antigravity",
  "antigravity-cli": "Antigravity CLI",
  junie: "Junie",
  kiro: "Kiro",
  grok: "Grok CLI",
  jcode: "jcode",
  augment: "Augment",
  "devin-cli": "Devin CLI",
  "devin-desktop": "Devin",
  omp: "oh-my-pi",
  kimchi: "Kimchi",
  senpi: "Senpi",
  "prime-agent": "Prime Agent",
  gjc: "gjc",
  commandcode: "Command Code",
  zcode: "Z Code",
  codebuddy: "CodeBuddy",
  workbuddy: "WorkBuddy",
  codebuff: "Codebuff",
  freebuff: "Freebuff",
  mux: "mux",
  trae: "Trae",
  fx: "fx",
  dsh: "dsh",
  reasonix: "Reasonix",
  mcode: "MiniMax Code",
  micode: "MiMo Code",
  cherrystudio: "Cherry Studio",
  opencodereview: "opencode review",
  lmstudio: "LM Studio",
  unsloth: "Unsloth Studio",
  hindsight: "Hindsight",
  muse: "Muse",
  synthetic: "Octofriend",
  proxy: "burnlog wrap",
  jsonl: "custom",
  "anthropic-api": "Anthropic API",
  "openai-api": "OpenAI API",
};

export function sourceLabel(source: string): string {
  return SOURCE_LABELS[source] ?? source;
}
